/**
 * Base seed (development/staging): reference data, catalog with images, suppliers & competing offers,
 * buyers, fleets and CMS content. Demo activity (orders, RFQs, shipments…) is generated by
 * `node dist/seed/demo-activity.js`, which drives the real services.
 *   pnpm db:seed
 */
import 'dotenv/config';
import { existsSync, readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PrismaPg } from '@prisma/adapter-pg';
import argon2 from 'argon2';
import sharp from 'sharp';
import { PrismaClient } from '../../src/generated/prisma/client.js';
import { buildSearchText } from '../../src/common/text/arabic.js';
import { BANNERS, BLOG_POSTS, blogBody, COUPONS, FAQS, HOME_SECTIONS, LANDING_STATS, PAGES, TESTIMONIALS } from './data/content.js';
import { BRANDS, CATEGORIES, MEDIA_EXTRA, PRODUCTS, type SeedProduct } from './data/catalog.js';
import { BUYERS, CITIES, DRIVERS, REGIONS, STAFF, SUPPLIERS } from './data/people.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const storageRoot = path.resolve(process.cwd(), process.env.STORAGE_LOCAL_DIR ?? './storage');
const mediaDir = path.join(here, 'media/files');
const manifest: Record<string, { file: string; creator: string | null; license: string; landingUrl: string | null; title: string | null }> = existsSync(path.join(here, 'media/manifest.json'))
  ? JSON.parse(readFileSync(path.join(here, 'media/manifest.json'), 'utf8'))
  : {};

if (process.env.APP_ENV === 'production') throw new Error('Refusing to run the demo seed in production');
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL as string }) });

/* ---------------------------------------------------------------- helpers */

function rng(seed: string) {
  let h = 1779033703 ^ seed.length;
  for (let i = 0; i < seed.length; i++) h = Math.imul(h ^ seed.charCodeAt(i), 3432918353) >>> 0;
  return () => {
    h = (h + 0x6d2b79f5) >>> 0;
    let t = h;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const round2 = (n: number) => Math.round(n * 100) / 100;

async function putPublic(key: string, buf: Buffer) {
  const file = path.join(storageRoot, 'public', key);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, buf);
}

/** Stores an image as webp + thumb/md variants and returns the StoredFile id. */
async function storeImage(key: string, input: Buffer, purpose: 'PRODUCT_IMAGE' | 'CATEGORY_IMAGE' | 'BRAND_LOGO' | 'SUPPLIER_LOGO' | 'BANNER' | 'BLOG_COVER', meta?: unknown): Promise<string> {
  const base = `seed/${key}`;
  const main = await sharp(input).resize({ width: 1600, withoutEnlargement: true }).webp({ quality: 84 }).toBuffer({ resolveWithObject: true });
  const thumb = await sharp(input).resize({ width: 360, withoutEnlargement: true }).webp({ quality: 80 }).toBuffer();
  const md = await sharp(input).resize({ width: 900, withoutEnlargement: true }).webp({ quality: 82 }).toBuffer();
  await Promise.all([putPublic(`${base}.webp`, main.data), putPublic(`${base}_thumb.webp`, thumb), putPublic(`${base}_md.webp`, md)]);
  const f = await prisma.storedFile.create({
    data: { visibility: 'PUBLIC', key: `${base}.webp`, mimeType: 'image/webp', sizeBytes: main.data.length, width: main.info.width, height: main.info.height, purpose, variants: { thumb: `${base}_thumb.webp`, md: `${base}_md.webp` }, meta: meta as never },
  });
  return f.id;
}

async function mediaImage(key: string, purpose: Parameters<typeof storeImage>[2], fallback: { label: string; color: string }): Promise<string> {
  const entry = manifest[key];
  if (entry && existsSync(path.join(mediaDir, entry.file))) {
    return storeImage(key, readFileSync(path.join(mediaDir, entry.file)), purpose, { credit: entry.creator, license: entry.license, source: entry.landingUrl, title: entry.title });
  }
  return storeImage(key, await placeholder(fallback.label, fallback.color), purpose);
}

/** Brand-styled placeholder (used when no photo is available). */
async function placeholder(label: string, color: string): Promise<Buffer> {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="900"><defs><linearGradient id="g" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="${color}"/><stop offset="1" stop-color="#0B2D5B"/></linearGradient></defs><rect width="900" height="900" fill="url(#g)"/><text x="450" y="500" font-family="Helvetica, Arial" font-size="120" font-weight="700" fill="#fff" text-anchor="middle">${label}</text></svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

/** Logo: rounded square with Latin initials in the organisation colour. */
async function logo(nameEn: string, color: string): Promise<Buffer> {
  const initials = nameEn
    .replace(/[^A-Za-z ]/g, '')
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0]?.toUpperCase())
    .join('');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="400" height="400" rx="88" fill="${color}"/><circle cx="330" cy="70" r="120" fill="#ffffff" opacity="0.08"/><text x="200" y="245" font-family="Helvetica, Arial" font-size="150" font-weight="800" fill="#fff" text-anchor="middle">${initials}</text></svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

/* ---------------------------------------------------------------- steps */

async function reset() {
  const tables = await prisma.$queryRaw<{ tablename: string }[]>`SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename <> '_prisma_migrations'`;
  await prisma.$executeRawUnsafe(`ALTER TABLE audit_logs DISABLE TRIGGER audit_logs_no_update`);
  await prisma.$executeRawUnsafe(`TRUNCATE ${tables.map((t) => `"${t.tablename}"`).join(', ')} RESTART IDENTITY CASCADE`);
  await prisma.$executeRawUnsafe(`ALTER TABLE audit_logs ENABLE TRIGGER audit_logs_no_update`);
}

async function seedGeo() {
  const regions = new Map<string, string>();
  for (const r of REGIONS) regions.set(r.code, (await prisma.region.create({ data: { code: r.code, nameAr: r.ar, nameEn: r.en } })).id);
  const cities = new Map<string, string>();
  for (const [i, c] of CITIES.entries()) {
    cities.set(c.slug, (await prisma.city.create({ data: { slug: c.slug, regionId: regions.get(c.region) as string, nameAr: c.ar, nameEn: c.en, lat: c.lat, lng: c.lng, sortOrder: i } })).id);
  }
  return cities;
}

async function seedStaff() {
  const hash = await argon2.hash('password', { type: argon2.argon2id });
  for (const s of STAFF) await prisma.user.create({ data: { type: 'STAFF', name: s.name, email: s.email, passwordHash: hash, staffRoles: s.roles as never, jobTitle: s.title } });
}

async function seedCatalog() {
  const categories = new Map<string, { id: string; parentSlug: string | null }>();
  for (const [i, c] of CATEGORIES.entries()) {
    const imageFileId = await mediaImage(`category-${c.slug}`, 'CATEGORY_IMAGE', { label: c.en, color: '#0A9B69' });
    const parent = await prisma.category.create({ data: { slug: c.slug, nameAr: c.ar, nameEn: c.en, icon: c.icon, imageFileId, sortOrder: i, isFeatured: !!c.featured } });
    categories.set(c.slug, { id: parent.id, parentSlug: null });
    for (const [j, child] of c.children.entries()) {
      const row = await prisma.category.create({ data: { slug: child.slug, nameAr: child.ar, nameEn: child.en, parentId: parent.id, sortOrder: j, imageFileId } });
      categories.set(child.slug, { id: row.id, parentSlug: c.slug });
    }
  }
  const brands = new Map<string, string>();
  for (const b of BRANDS) {
    const logoFileId = await storeImage(`brand-${b.slug}`, await logo(b.en, b.color), 'BRAND_LOGO');
    brands.set(b.slug, (await prisma.brand.create({ data: { slug: b.slug, nameAr: b.ar, nameEn: b.en, originCountry: b.origin ?? null, isFeatured: !!b.featured, logoFileId } })).id);
  }
  const products = new Map<string, { id: string; units: { id: string; qty: number; code: string }[]; seed: SeedProduct; parentCat: string }>();
  for (const [i, p] of PRODUCTS.entries()) {
    const cat = categories.get(p.cat);
    if (!cat) throw new Error(`Unknown category ${p.cat}`);
    const brand = p.brand ? BRANDS.find((b) => b.slug === p.brand) : undefined;
    const catDef = CATEGORIES.find((c) => c.slug === (cat.parentSlug ?? p.cat));
    const fileId = await mediaImage(`product-${p.slug}`, 'PRODUCT_IMAGE', { label: p.en.split(' ').slice(0, 2).join(' '), color: brand?.color ?? '#0A9B69' });
    const product = await prisma.product.create({
      data: {
        slug: p.slug,
        sku: `TW-${String(1000 + i)}`,
        barcode: `628${String(100000000 + i * 7919).slice(0, 10)}`,
        categoryId: cat.id,
        brandId: p.brand ? brands.get(p.brand) ?? null : null,
        nameAr: p.ar,
        nameEn: p.en,
        descriptionAr: p.descAr,
        descriptionEn: p.descEn,
        originCountry: p.origin,
        storageType: p.storage ?? 'AMBIENT',
        specs: p.specs.map(([keyAr, keyEn, valueAr, valueEn]) => ({ keyAr, keyEn, valueAr, valueEn })),
        tags: p.tags ?? [],
        isFeatured: !!p.featured,
        status: 'ACTIVE',
        searchText: buildSearchText(p.ar, p.en, brand?.ar, brand?.en, catDef?.ar, catDef?.en, (p.tags ?? []).join(' ')),
        images: { create: [{ fileId, sortOrder: 0, altAr: p.ar, altEn: p.en }] },
        createdAt: new Date(Date.now() - (PRODUCTS.length - i) * 3_600_000 * 6),
      },
    });
    const units = [];
    for (const [j, u] of p.units.entries()) {
      const unit = await prisma.productUnit.create({ data: { productId: product.id, code: u.code, nameAr: u.ar, nameEn: u.en, baseQuantity: u.qty, baseUnitAr: u.baseAr, baseUnitEn: u.baseEn, weightKg: u.weightKg ?? null, isDefault: j === 0, sortOrder: j } });
      units.push({ id: unit.id, qty: u.qty, code: u.code });
    }
    products.set(p.slug, { id: product.id, units, seed: p, parentCat: cat.parentSlug ?? p.cat });
  }
  return { categories, products };
}

async function seedSuppliers(cities: Map<string, string>, products: Awaited<ReturnType<typeof seedCatalog>>['products']) {
  const suppliers = new Map<string, string>();
  const now = Date.now();
  for (const s of SUPPLIERS) {
    const r = rng(s.slug);
    const logoFileId = await storeImage(`supplier-${s.slug}`, await logo(s.en, s.color), 'SUPPLIER_LOGO');
    const owner = await prisma.user.create({ data: { type: 'SUPPLIER', name: s.owner.name, phone: s.owner.phone, phoneVerifiedAt: new Date() } });
    const supplier = await prisma.supplier.create({
      data: {
        slug: s.slug,
        nameAr: s.ar,
        nameEn: s.en,
        legalName: s.legal,
        descriptionAr: s.descAr,
        descriptionEn: s.descEn,
        logoFileId,
        crNumber: s.cr,
        vatNumber: s.vat,
        // 22 digits from one draw (String(n * 1e22) would switch to exponent notation).
        iban: `SA${r().toFixed(20).slice(2).padEnd(22, '0')}`,
        bankName: 'مصرف الراجحي',
        beneficiaryName: s.legal,
        commissionRate: s.commission,
        minOrderValue: s.minOrder,
        fleetMode: s.fleet,
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        ratingAvg: s.rating,
        ratingCount: s.ratingCount,
        contactPhone: s.owner.phone,
        contactEmail: `sales@${s.slug}.test`,
        cityId: cities.get(s.city) ?? null,
        isFeatured: s.featured,
        foundedYear: s.founded,
        searchText: buildSearchText(s.ar, s.en, s.cr),
        members: { create: [{ userId: owner.id, role: 'OWNER', status: 'ACTIVE' }] },
        warehouses: { create: [{ name: s.warehouse.name, cityId: cities.get(s.city) as string, district: s.warehouse.district, lat: s.warehouse.lat, lng: s.warehouse.lng, contactPhone: s.owner.phone, isDefault: true }] },
        coverage: {
          create: s.coverage.map((c) => ({ cityId: cities.get(c.city) as string, deliveryFee: c.fee, freeDeliveryThreshold: c.free, leadTimeDays: c.lead, sameDayAvailable: !!c.sameDay, cutoffTime: c.sameDay ? '13:00' : null })),
        },
      },
    });
    suppliers.set(s.slug, supplier.id);

    // Offers on eligible products (category or sub-category match), deterministic subset & price variation.
    for (const [slug, p] of products) {
      const eligible = s.categories.includes(p.seed.cat) || s.categories.includes(p.parentCat);
      if (!eligible || r() > s.share) continue;
      const unitIdx = p.units.length > 1 && s.slug === 'golden-grain-group' ? p.units.length - 1 : r() < 0.25 && p.units.length > 1 ? 1 : 0;
      const chosen = [unitIdx, ...(s.slug === 'tawreed-direct' || p.units.length < 2 || r() > 0.35 ? [] : [unitIdx === 0 ? 1 : 0])];
      for (const idx of chosen) {
        const unit = p.units[idx];
        if (!unit) continue;
        const factor = s.priceFactor * (0.95 + r() * 0.12);
        const price = round2(p.seed.base * unit.qty * factor);
        const moq = p.seed.moq?.[idx] ?? (unit.code === 'KG' ? 25 : 1);
        const onRequest = unit.code === 'TON' || unit.code === 'PALLET';
        const compareAt = r() < 0.2 ? round2(price * (1.08 + r() * 0.1)) : null;
        const offer = await prisma.offer.create({
          data: {
            supplierId: supplier.id,
            productId: p.id,
            productUnitId: unit.id,
            sku: `${s.slug.slice(0, 3).toUpperCase()}-${slug.slice(0, 12)}-${idx}`,
            price,
            compareAtPrice: compareAt,
            minOrderQty: moq,
            qtyStep: unit.code === 'KG' ? 25 : 1,
            maxOrderQty: null,
            stockMode: onRequest ? 'ON_REQUEST' : p.seed.cat === 'water' ? 'UNLIMITED' : 'TRACKED',
            stockQty: onRequest ? 0 : Math.round(moq * (60 + r() * 240)),
            leadTimeDays: onRequest ? 3 : null,
            status: 'ACTIVE',
            tiers: moq >= 1 ? { create: [{ minQty: moq * 5, price: round2(price * 0.97) }, { minQty: moq * 12, price: round2(price * 0.94) }] } : undefined,
          },
        });
        if (r() < 0.12 && !onRequest) {
          await prisma.deal.create({
            data: {
              offerId: offer.id,
              supplierId: supplier.id,
              titleAr: 'عرض لفترة محدودة',
              titleEn: 'Limited-time deal',
              dealPrice: round2(price * (0.86 + r() * 0.06)),
              startsAt: new Date(now - 86_400_000),
              endsAt: new Date(now + (2 + Math.floor(r() * 6)) * 86_400_000),
              maxQtyPerOrder: moq * 20,
              totalQtyCap: moq * 400,
              status: 'APPROVED',
            },
          });
        }
      }
    }
  }
  // A second team member for the first supplier (sales).
  const sales = await prisma.user.create({ data: { type: 'SUPPLIER', name: 'ليان التميمي', phone: '+966500000191' } });
  await prisma.supplierMember.create({ data: { supplierId: suppliers.get('al-waha-foods') as string, userId: sales.id, role: 'SALES', status: 'ACTIVE' } });
  // A pending application to demo the approval flow.
  await prisma.supplierApplication.create({ data: { companyName: 'مصنع الريادة للمعكرونة', contactName: 'إبراهيم العمري', phone: '+966500000150', email: 'info@riyada-pasta.test', cityId: cities.get('riyadh') ?? null, categories: ['المعكرونة', 'البقوليات'], crNumber: '1010999001', message: 'نرغب بعرض منتجات المعكرونة والشعيرية لعملاء المطاعم.' } });
  return suppliers;
}

async function refreshProductStats() {
  await prisma.$executeRaw`
    UPDATE products p SET "offersCount" = s.cnt, "minPrice" = s.minp, "maxPrice" = s.maxp
    FROM (
      SELECT o."productId" pid, COUNT(*) cnt, MIN(COALESCE(d."dealPrice", o.price)) minp, MAX(o.price) maxp
      FROM offers o LEFT JOIN deals d ON d."offerId" = o.id AND d.status = 'APPROVED' AND d."startsAt" <= now() AND d."endsAt" > now()
      WHERE o.status = 'ACTIVE' AND o."deletedAt" IS NULL GROUP BY o."productId"
    ) s WHERE s.pid = p.id`;
}

async function seedBuyers(cities: Map<string, string>) {
  for (const b of BUYERS) {
    const users = [];
    for (const m of b.members) users.push({ m, user: await prisma.user.create({ data: { type: 'BUYER', name: m.name, phone: m.phone, email: m.email ?? null, phoneVerifiedAt: new Date() } }) });
    const cityId = cities.get(b.city) as string;
    await prisma.buyerCompany.create({
      data: {
        name: b.name,
        legalName: b.legal,
        businessType: b.type,
        crNumber: b.cr,
        vatNumber: b.vat,
        cityId,
        phone: b.members[0]?.phone,
        email: b.members[0]?.email ?? null,
        verificationStatus: b.verification,
        verifiedAt: b.verification === 'VERIFIED' ? new Date(Date.now() - 40 * 86_400_000) : null,
        branchesCount: b.branches,
        searchText: buildSearchText(b.name, b.legal, b.cr),
        createdAt: new Date(Date.now() - 60 * 86_400_000),
        members: { create: users.map(({ m, user }) => ({ userId: user.id, role: m.role, status: 'ACTIVE' })) },
        addresses: {
          create: [{
            label: b.address.label,
            recipientName: b.members[0]?.name ?? b.name,
            recipientPhone: b.members[0]?.phone ?? '+966500000000',
            cityId,
            district: b.address.district,
            street: b.address.street,
            buildingNumber: b.address.building,
            postalCode: b.address.postal,
            shortAddress: b.address.short,
            lat: b.address.lat,
            lng: b.address.lng,
            isDefault: true,
          }],
        },
        creditAccount: {
          create: b.credit
            ? { status: 'ACTIVE', creditLimit: b.credit.limit, termsDays: b.credit.terms, riskLevel: 'LOW', approvedAt: new Date(Date.now() - 30 * 86_400_000) }
            : { status: 'NO_CREDIT' },
        },
      },
    });
  }
}

async function seedFleets(suppliers: Map<string, string>) {
  for (const d of DRIVERS) {
    const supplierId = d.fleet === 'PLATFORM' ? null : suppliers.get(d.fleet) ?? null;
    const ownerType = supplierId ? 'SUPPLIER' : 'PLATFORM';
    const vehicle = await prisma.vehicle.create({ data: { ownerType, supplierId, plateNumber: d.plate, type: d.vehicle, capacityKg: d.capacity, refrigerated: d.reefer } });
    const user = await prisma.user.create({ data: { type: 'DRIVER', name: d.name, phone: d.phone, phoneVerifiedAt: new Date() } });
    await prisma.driver.create({ data: { userId: user.id, ownerType, supplierId, vehicleId: vehicle.id, licenseNumber: `LIC-${d.phone.slice(-4)}`, nationalId: `2${d.phone.slice(-9)}`, ratingAvg: 4.7, deliveriesCount: 40 + Number(d.phone.slice(-2)) } });
  }
}

async function seedContent(categories: Map<string, { id: string }>) {
  for (const [i, s] of LANDING_STATS.entries()) await prisma.landingStat.create({ data: { key: s.key, labelAr: s.ar, labelEn: s.en, value: s.value, suffix: s.suffix || null, sortOrder: i } });
  for (const [i, t] of TESTIMONIALS.entries()) await prisma.testimonial.create({ data: { nameAr: t.nameAr, nameEn: t.nameEn, roleAr: t.roleAr, roleEn: t.roleEn, companyAr: t.companyAr, companyEn: t.companyEn, businessType: t.type as never, quoteAr: t.quoteAr, quoteEn: t.quoteEn, sortOrder: i } });
  for (const [i, f] of FAQS.entries()) await prisma.faq.create({ data: { audience: f.audience, category: f.category, questionAr: f.qAr, questionEn: f.qEn, answerAr: f.aAr, answerEn: f.aEn, sortOrder: i } });
  for (const p of PAGES) await prisma.cmsPage.create({ data: { slug: p.slug, titleAr: p.titleAr, titleEn: p.titleEn, bodyAr: p.bodyAr, bodyEn: p.bodyEn } });
  for (const [i, b] of BLOG_POSTS.entries()) {
    const coverFileId = await mediaImage(b.cover, 'BLOG_COVER', { label: 'Tawreed', color: '#0B2D5B' });
    await prisma.blogPost.create({
      data: { slug: b.slug, titleAr: b.titleAr, titleEn: b.titleEn, excerptAr: b.excerptAr, excerptEn: b.excerptEn, bodyAr: blogBody(b.titleAr, b.excerptAr), bodyEn: `## ${b.titleEn}\n\n${b.excerptEn}\n\nPractical guidance for Saudi businesses, from the Tawreed team.`, coverFileId, tags: b.tags, authorName: 'فريق توريد', status: 'PUBLISHED', publishedAt: new Date(Date.now() - (i + 1) * 5 * 86_400_000), readingMinutes: 4 + i },
    });
  }
  for (const [i, b] of BANNERS.entries()) {
    const imageFileId = await mediaImage(b.image, 'BANNER', { label: 'Tawreed', color: '#067A5B' });
    const [linkType, linkValue] = b.link;
    await prisma.banner.create({ data: { placement: b.placement as never, titleAr: b.titleAr, titleEn: b.titleEn, subtitleAr: b.subAr, subtitleEn: b.subEn, ctaLabelAr: b.ctaAr, ctaLabelEn: b.ctaEn, imageFileId, linkType: linkType as never, linkValue: linkValue || null, sortOrder: i } });
  }
  // Marketing photos the websites reference directly by key (/files/p/seed/<key>_md.webp).
  const bannerKeys = new Set<string>(BANNERS.map((b) => b.image));
  for (const m of MEDIA_EXTRA) if (!bannerKeys.has(m.key) && !m.key.startsWith('blog-')) await mediaImage(m.key, 'BANNER', { label: 'Tawreed', color: '#067A5B' });
  for (const [i, s] of HOME_SECTIONS.entries()) await prisma.homeSection.create({ data: { type: s.type as never, titleAr: s.ar, titleEn: s.en, config: s.config, sortOrder: i } });
  for (const c of COUPONS) {
    await prisma.coupon.create({ data: { code: c.code, type: c.type as never, value: c.value, maxDiscount: c.max, minOrderValue: c.min, firstOrderOnly: c.firstOrderOnly, perCompanyLimit: c.perCompany, descriptionAr: c.ar, descriptionEn: c.en, endsAt: new Date(Date.now() + 180 * 86_400_000) } });
  }
  void categories;
}

async function main() {
  const t0 = Date.now();
  console.log('Seeding Tawreed…');
  await reset();
  const cities = await seedGeo();
  await seedStaff();
  const { categories, products } = await seedCatalog();
  console.log(`  catalog: ${categories.size} categories, ${products.size} products`);
  const suppliers = await seedSuppliers(cities, products);
  await refreshProductStats();
  console.log(`  suppliers: ${suppliers.size}, offers: ${await prisma.offer.count()}, deals: ${await prisma.deal.count()}`);
  await seedBuyers(cities);
  await seedFleets(suppliers);
  await seedContent(categories);
  console.log(`Base seed done in ${((Date.now() - t0) / 1000).toFixed(1)}s. Next: node dist/seed/demo-activity.js (pnpm db:seed runs both).`);
}

await main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
